import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/frontend/NavBar";
import Footer from "@/components/frontend/Footer";
import { Toaster } from "react-hot-toast";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { extractRouterConfig } from "uploadthing/server";
import { ourFileRouter } from "./api/uploadthing/core";
// import { CartProvider } from "@/components/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
      {/* <CartProvider> */}

      <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
        <NavBar />
        {children}
        <Footer/>
        <Toaster position='top-center' />
        {/* </CartProvider> */}

      </body>
    </html>
  );
}
